name: Deploy
on:
    workflow_dispatch: 
jobs:
    Dev:
      uses: ./.github/workflows/release-template.yaml
      with:
         namespace: "dev"
         deployment: "Devlopement"
         branch: "dev"
         environment: "Dev"
      secrets:
        KUBE_CONFIG: ${{secrets.KUBE_CONFIG_DEV}}
    PROD:
      needs: [Dev]
      uses: ./.github/workflows/release-template.yaml
      with:
         namespace: "prod"
         deployment: "Production"
         branch: "prod"
         environment: "PROD"         
      secrets:
        KUBE_CONFIG: ${{secrets.KUBE_CONFIG_PROD}}
