name: Deploy
on:
    workflow_dispatch: 
        inputs:
            environment: 
                type: environment
                description: "Environment"
jobs:
    Deploy:
      environment: ${{ github.event.inputs.environment}}
      uses: ./.github/workflows/release-template.yaml
      with:
         namespace: ${{ vars.Namespace}}
         deployment: ${{ vars.Deployment}}
         branch: ${{ vars.Branch}}          
      secrets:
         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
